import type { SensorsRegistry } from './ha/types.js';

export const POOL_SENSORS: SensorsRegistry = {
  // --- Essential Water Chemistry ---
  temperature: {
    name: 'Temperature',
    unit: '°C',
    setpoint: 27,
    step: 1,
    mode: 'heatflow',
    category: 'water_chemistry',
  },
  orp: {
    name: 'ORP',
    unit: 'mV',
    setpoint: 700,
    step: 50,
    mode: 'centric',
    min_limit: 0,
    category: 'water_chemistry',
  },
  ec: {
    name: 'Electrical Conductivity',
    unit: 'µS/cm',
    setpoint: 4000,
    step: 200,
    mode: 'centric',
    min_limit: 0,
    category: 'water_chemistry',
  },
  tds: {
    name: 'TDS',
    unit: 'g/L',
    setpoint: 5,
    step: 0.5,
    mode: 'centric',
    min_limit: 0,
    category: 'water_chemistry',
  },
  ph: {
    name: 'pH',
    unit: 'pH',
    setpoint: 7.2,
    step: 0.2,
    mode: 'centric',
    min_limit: 0,
    category: 'water_chemistry',
  },

  // --- Chemical Balance ---
  salinity: {
    name: 'Salinity',
    unit: 'ppm',
    setpoint: 3000,
    step: 500,
    mode: 'centric',
    min_limit: 0,
    category: 'chemical_balance',
  },
  cya: {
    name: 'Cyanuric Acid',
    unit: 'ppm',
    setpoint: 40,
    step: 10,
    mode: 'centric',
    min_limit: 0,
    category: 'chemical_balance',
  },
  calcium: {
    name: 'Calcium',
    unit: 'ppm',
    setpoint: 300,
    step: 100,
    mode: 'centric',
    min_limit: 0,
    category: 'chemical_balance',
  },
  phosphate: {
    name: 'Phosphate',
    unit: 'ppb',
    setpoint: 50,
    step: 10,
    mode: 'centric',
    min_limit: 0,
    category: 'chemical_balance',
  },
  alkalinity: {
    name: 'Alkalinity',
    unit: 'ppm',
    setpoint: 100,
    step: 20,
    mode: 'centric',
    min_limit: 0,
    category: 'chemical_balance',
  },

  // --- Treatment & Sanitization ---
  free_chlorine: {
    name: 'Free Chlorine',
    unit: 'ppm',
    setpoint: 3,
    step: 0.5,
    mode: 'centric',
    min_limit: 0,
    category: 'treatment',
  },
  total_chlorine: {
    name: 'Total Chlorine',
    unit: 'ppm',
    setpoint: 3,
    step: 0.5,
    mode: 'centric',
    min_limit: 0,
    category: 'treatment',
  },
  bromine: {
    name: 'Bromine',
    unit: 'ppm',
    setpoint: 4,
    step: 1,
    mode: 'centric',
    min_limit: 0,
    category: 'treatment',
  },
  pressure: {
    name: 'Filter Pressure',
    unit: 'psi',
    setpoint: 12,
    step: 2,
    mode: 'centric',
    category: 'treatment',
  },
  specific_gravity: {
    name: 'Specific Gravity',
    unit: 'sg',
    setpoint: 1.1,
    step: 0.2,
    mode: 'centric',
    category: 'treatment',
  },
  magnesium: {
    name: 'Magnesium',
    unit: 'ppm',
    setpoint: 1200,
    step: 100,
    mode: 'centric',
    min_limit: 0,
    category: 'treatment',
  },
  chlorinator: {
    name: 'Chlorinator Setting',
    unit: '%',
    setpoint: 50,
    step: 10,
    mode: 'heatflow',
    min_limit: 0,
    category: 'treatment',
  },

  // --- Equipment & Maintenance ---
  water_level: {
    name: 'Water Level',
    unit: '%',
    setpoint: 100,
    step: 10,
    mode: 'centric',
    min_limit: 0,
    category: 'equipment',
  },
  flow_rate: {
    name: 'Flow Rate',
    unit: 'm³/h',
    setpoint: 10,
    step: 1,
    mode: 'centric',
    min_limit: 0,
    category: 'equipment',
  },
  uv_radiation: {
    name: 'UV Radiation',
    unit: 'mW/cm²',
    setpoint: 4,
    step: 1,
    mode: 'centric',
    min_limit: 0,
    category: 'equipment',
  },
  product_volume: {
    name: 'Product Volume',
    unit: 'L',
    setpoint: 20,
    step: 5,
    mode: 'centric',
    min_limit: 0,
    category: 'equipment',
  },
  product_weight: {
    name: 'Product Weight',
    unit: 'kg',
    setpoint: 25,
    step: 5,
    mode: 'centric',
    min_limit: 0,
    category: 'equipment',
  },
  pump_speed: {
    name: 'Pump Speed',
    unit: '%',
    setpoint: 50,
    step: 10,
    mode: 'heatflow',
    min_limit: 0,
    category: 'equipment',
  },
  light_brightness: {
    name: 'Light Brightness',
    unit: '%',
    setpoint: 80,
    step: 10,
    mode: 'heatflow',
    min_limit: 0,
    category: 'equipment',
  },
  heat_pump_setpoint: {
    name: 'Heat Pump Setpoint',
    unit: '°C',
    setpoint: 28,
    step: 1,
    mode: 'centric',
    min_limit: 10,
    category: 'equipment',
  },
};
